version: '3.0'
services:
    zoo1:
        image: zookeeper:3.4.12
        restart: "no"
        hostname: zoo1
        container_name: zoo1
        expose:
            - 2181
        ports:
            - 2181:2181
        environment:
            ZOO_MY_ID: 1
            ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888

    zoo2:
        image: zookeeper:3.4.12
        restart: "no"
        hostname: zoo2
        container_name: zoo2
        expose:
            - 2181
        ports:
            - 2182:2181
        environment:
            ZOO_MY_ID: 2
            ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=0.0.0.0:2888:3888 server.3=zoo3:2888:3888

    zoo3:
        image: zookeeper:3.4.12
        restart: "no"
        hostname: zoo3
        container_name: zoo3
        expose:
            - 2181
        ports:
            - 2183:2181
        environment:
            ZOO_MY_ID: 3
            ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=0.0.0.0:2888:3888
    #https://www.elkozmon.com/zoonavigator/get-started/usage/
    api:
        image: elkozmon/zoonavigator-api:0.5.0
        container_name: zoonavigator-api
        environment:
            API_HTTP_PORT: 9000
        restart: "no"
    web:
        image: elkozmon/zoonavigator-web:0.5.0
        container_name: zoonavigator-web
        depends_on:
            - api
            - zoo1
            - zoo2
            - zoo3
        ports:
            - "8000:8000"
        environment:
            WEB_HTTP_PORT: 8000
            API_HOST: "api"
            API_PORT: 9000
        restart: "no"
    kafka1:
        image: aopazo:kafka
        restart: "no"
        hostname: kafka1
        container_name: kafka1
        depends_on:
            - zoo1
            - zoo2
            - zoo3
        expose:
            #listeners
            - "9072"
            - "9062"
        #HOST:CONTAINER
        ports:
            - 9072:9072
            - 9062:9062
        entrypoint:
            - /usr/local/kafka/bin/kafka-server-start.sh
            - /usr/local/kafka/config/server.properties
        volumes:
            #HOST:CONTAINMER
            - ./config_kafka1:/usr/local/kafka/config
    kafka2:
        image: aopazo:kafka
        restart: "no"
        hostname: kafka2
        container_name: kafka2
        depends_on:
            - kafka1
        expose:
            - "9073"
            - "9063"
        ports:
            - 9073:9073
            - 9063:9063
        entrypoint:
            - /usr/local/kafka/bin/kafka-server-start.sh
            - /usr/local/kafka/config/server.properties
        volumes:
            #HOST:CONTAINMER
            - ./config_kafka2:/usr/local/kafka/config
    kafka3:
        image: aopazo:kafka
        restart: "no"
        hostname: kafka3
        container_name: kafka3
        depends_on:
            - kafka2
        expose:
            - "9074"
            - "9064"
        ports:
            - 9074:9074
            - 9064:9064
        entrypoint:
            - /usr/local/kafka/bin/kafka-server-start.sh
            - /usr/local/kafka/config/server.properties
        volumes:
            #HOST:CONTAINMER
            - ./config_kafka3:/usr/local/kafka/config
networks:
  kafka-network:
    driver: bridge
